### ISSUE TITLE
Installing dotnet-ef fails on Azure Pipelines builds

### ISSUE THREAD

**Issue by dannyyy** [pekspro/EF-Migrations-Script-Generator-Task#12] opened 2019-11-17 17:59 UTC
Trying to install the necessary tools will fail because the tooling is just available after a session restart.

```
Starting: Generate Migration Script
==============================================================================
Task         : Entity Framework Core Migrations Script Generator
Description  : Tool for projects that use Entity Framework Core Code-First. Generates migration scripts which can be used to update a database (for instance with the task 'Azure SQL Database Deployment').
Version      : 0.0.30
Author       : PEK's Productions
Help         : [More Information](https://github.com/pekspro/EF-Migrations-Script-Generator-Task)
==============================================================================
Project path: /home/vsts/work/1/s/MyProject.Model
Start-up project path: /home/vsts/work/1/s/MyProject/MyProject.WebUI
Target folder: /home/vsts/work/1/a/migrations
Number of database contexts: 1
Checking of dotnet-ef is installed.
/usr/bin/dotnet tool list --global
Package Id      Version      Commands
-------------------------------------

Installing dotnet-ef as global tool.
/usr/bin/dotnet tool install --global dotnet-ef
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.

Generating migration script for DbCon in project /home/vsts/work/1/s/MyProject/MyProject.Model
/usr/bin/dotnet ef migrations script --idempotent --project /home/vsts/work/1/s/MyProject/MyProject.Model --startup-project /home/vsts/work/1/s/MyProject/MyProject.WebUI --output /home/vsts/work/1/a/migrations/DbCon.sql --context DbCon --verbose
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

##[error]The process '/usr/bin/dotnet' failed with exit code 1
Finishing: Generate Migration Script

```

**Comment by pekspro** [comment] 2019-11-17 19:04
That's interesting, I haven't seen this before:

    Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.

What kind of agent are you using for building? Also, are you doing some manual installation of .NET Core SDK earlier in the pipeline?

**Comment by dannyyy** [comment] 2019-11-17 19:43
I'm using the Azure hosted 'ubuntu-latest' image.

Prior to this task I have some dotnet restore, build and test tasks. I'm using .NET 3.0 but without using a .NET Core SDK task in the pipeline.

In the mean time I tried to split the installation and the generation. Without sucess
1. DotNetCore task to install the tool
2. Your task to generate the script

```
Starting: Install dotnet ef
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/usr/bin/dotnet tool install -g --configfile NuGet_Only.conf dotnet-ef
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.
Finishing: Install dotnet ef
```

```
Starting: Generate Migration Script
==============================================================================
Task         : Entity Framework Core Migrations Script Generator
Description  : Tool for projects that use Entity Framework Core Code-First. Generates migration scripts which can be used to update a database (for instance with the task 'Azure SQL Database Deployment').
Version      : 0.0.30
Author       : PEK's Productions
Help         : [More Information](https://github.com/pekspro/EF-Migrations-Script-Generator-Task)
==============================================================================
Project path: /home/vsts/work/1/s/MyProject/MyProject.Model
Start-up project path: /home/vsts/work/1/s/MyProject/MyProject.WebUI
Target folder: /home/vsts/work/1/a/migrations
Number of database contexts: 1
Checking of dotnet-ef is installed.
/usr/bin/dotnet tool list --global
Package Id      Version      Commands 
--------------------------------------
dotnet-ef       3.0.0        dotnet-ef

dotnet-ef is already installed.
Generating migration script for DbCon in project /home/vsts/work/1/s/MyProject/MeProject.Model
/usr/bin/dotnet ef migrations script --idempotent --project /home/vsts/work/1/s/MyProject/MyProject.Model --startup-project /home/vsts/work/1/s/MyProject/MyProject.WebUI --output /home/vsts/work/1/a/migrations/DbCon.sql --context DbCon --verbose
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

##[error]The process '/usr/bin/dotnet' failed with exit code 1
Finishing: Generate Migration Script
```

My next try is to put an `source .bashrc` in between. Maybe this helps to reload the session.

Then I have another request (will open a new issue for that later):  
Since my `NuGet.config` contains some private repositories with authentication, your task is not able to run smoothly. Either I have to disable all my private repositories and enable again after your task. Or the suggested solution, that your task will allow to specify a `NuGet.config` file. Then `dotnet tool install` provides the argument `--configfile`.

Thank you very much.

**Comment by dannyyy** [comment] 2019-11-17 21:13
I have found a solution. Using `windows-2019` is working as expected.
If you offer the possibility to use another `--configfile Nuget.Config` then I can get rid of the first of these two tasks.

```
          - task: DotNetCoreCLI@2
            displayName: "Install dotnet ef"
            inputs:
              command: custom
              custom: tool
              arguments: install -g --configfile NuGet_Only.conf dotnet-ef
          - task: pekspro.pekspro-efcore-migration-script-generator.efcore-migration-script-generator.efcore-migration-script-generator-task@0
            displayName: 'Generate Migration Script'
            #condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
            inputs:
              projectpath: tpc.eMedia.MyProject/tpc.eMedia.MyProject.Model
              databasecontexts: DbCon
              startupprojectpath: tpc.eMedia.MyProject/tpc.eMedia.MyProject.WebUI
              installdependencies: false
```

**Comment by pekspro** [comment] 2019-11-18 17:34
It’s nice that you found a workaround. But still, this shouldn’t be necessary. I found a discussion here were it is proposed to add `$HOME/.dotnet/tools` to the `PATH` variable:

https://github.com/microsoft/azure-pipelines-tasks/issues/8291

Another work around is to install the tool in a specific `tool-path`:

https://developercommunity.visualstudio.com/content/problem/340067/install-global-tool.html?childToView=343864#comment-343864

A third suggestion is to install the SDK before installing the tool:

https://github.com/dotnet/cli/issues/8368#issuecomment-424852996

This might be the best solution. I think I should be able to detect if `Since you just installed the .NET Core SDK` is printed, and if that’s the case I could probably show a better error message in the log.


Do you have any thoughts about these? I’m a bit busy right now and haven’t been able to replicate the problem so far so I can’t create any fast solution right now.

**Comment by pekspro** [comment] 2020-01-25 09:13
I’m closing this since I’m not able to replicate this. That said, I’m still considering doing #13 .

**Closed by pekspro** 2020-01-25 09:13 UTC

**Comment by Ric43** [comment] 2020-02-21 09:27
I am having the same issue as the above. Entity Framework Core Migrations Script Generator out the box. .NET core 3.1. Specified project with migrations, dbcontext class and startup project. Target folder is default. I checked the option to install .NET Core 3 dependencies.
Specified version 3.1.0. Task is run after my checkout, restore and build tasks. Error is 100% reproducible.

Error Message:
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by Ric43** [comment] 2020-02-21 09:29
Sorry, should also have mention, agend specification is ubuntu-16.04

**Comment by Ric43** [comment] 2020-02-21 10:18
I got this to work using workaround 3 above. I left the settings on the migration script generator unchanged.
I added the Use .NET SDK task between my build and generate migration script tasks.
Following the documentation for Use .NET SDK task, I used version 2.x =>.
That failed with:
##[error]Version 2.x => is not allowed. Allowed version types are: majorVersion.x, majorVersion.minorVersion.x, majorVersion.minorVersion.patchVersion.
Tried again with version 3.1.102.
That time it worked and the Generate migration script task worked.

**Comment by pekspro** [comment] 2020-02-22 09:18
Thanks for the report @Ric43. I will have another look on this later. maybe I could catch this error and show a more descriptive error message instead.

**Comment by Uffman** [comment] 2020-03-22 23:02
I am having the same issues and what @Ric43 recommended is not working for me.

**Comment by Uffman** [comment] 2020-03-23 08:15
This worker for me:
[https://github.com/microsoft/azure-pipelines-tasks/issues/12548](https://github.com/microsoft/azure-pipelines-tasks/issues/12548)

**Comment by edswangren** [comment] 2020-12-08 17:27
Same problem for me out of the box using a linux agent. Windows works.
